-- MySQL Script generated by MySQL Workbench
-- Sun Jun 30 15:17:13 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema uliveto
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema uliveto
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `uliveto` DEFAULT CHARACTER SET utf8 ;
USE `uliveto` ;

-- -----------------------------------------------------
-- Table `uliveto`.`utenti`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `uliveto`.`utenti` ;

CREATE TABLE IF NOT EXISTS `uliveto`.`utenti` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `uliveto`.`ordini`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `uliveto`.`ordini` ;

CREATE TABLE IF NOT EXISTS `uliveto`.`ordini` (
  `o_id` INT NOT NULL AUTO_INCREMENT,
  `p_id` INT NOT NULL,
  `u_id` INT NOT NULL,
  `o_quantity` INT NOT NULL,
  `o_date` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`o_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `uliveto`.`prodotti`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `uliveto`.`prodotti` ;

CREATE TABLE IF NOT EXISTS `uliveto`.`prodotti` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `descrizione` LONGTEXT NOT NULL,
  `categoria` VARCHAR(200) NOT NULL,
  `stock` INTEGER NOT NULL,
  `prezzo` DOUBLE NOT NULL,
  `immagine` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`, `nome`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `uliveto`.`utenti`
-- -----------------------------------------------------
START TRANSACTION;
USE `uliveto`;
INSERT INTO `uliveto`.`utenti` (`id`, `nome`, `email`, `password`) VALUES (1, 'gabriele', 'gabriele.cicalese2004@gmail.com', '1234');
INSERT INTO `uliveto`.`utenti` (`id`, `nome`, `email`, `password`) VALUES (2, 'ADMIN', 'admin@gmail.com', 'admin');

COMMIT;

-- -----------------------------------------------------
-- Data for table `uliveto`.`prodotti`
-- -----------------------------------------------------

START TRANSACTION;
USE `uliveto`;
INSERT INTO `uliveto`.`prodotti` (`id`, `nome`, `categoria`,`descrizione`,`stock`,`prezzo`, `immagine`) VALUES (1, 'Olio Extravergine di oliva 250ml', 'oli','BOTTIGLIA DI VETRO DA 250 ML CON TAPPO ANTIRABBOCCO',0,'6', 'olio_extravergine_oliva_250.jpg');
INSERT INTO `uliveto`.`prodotti` (`id`, `nome`, `categoria`,`descrizione`,`stock`, `prezzo`, `immagine`) VALUES (2, 'Olio Extravergine di oliva 500ml', 'oli','BOTTIGLIA DI VETRO DA 500 ML CON TAPPO ANTIRABBOCCO',20,'11' ,'olio_extravergine_oliva_500.jpg');
INSERT INTO `uliveto`.`prodotti` (`id`, `nome`, `categoria`,`descrizione`,`stock`, `prezzo`, `immagine`) VALUES (3, 'Olio Extravergine di oliva 5L', 'oli','FUSTINO DA 5 LITRI OLIO EXTRAVERGINE DI OLIVA','20' ,'60','olio_extravergine_oliva_5lt.jpg');
INSERT INTO `uliveto`.`prodotti` (`id`, `nome`, `categoria`,`descrizione`,`stock`, `prezzo`, `immagine`) VALUES (4, 'Confezione Olio Extravergine di oliva 250ml', 'oli','SCATOLA DA 6 BOTTIGLIE DI VETRO DA 250 ML CON TAPPO ANTIRABBOCCO ( TOT 3 LITRI )',20,'66' ,'olio_extravergine_oliva_250_scatola.jpg');
INSERT INTO `uliveto`.`prodotti` (`id`, `nome`, `categoria`,`descrizione`,`stock`, `prezzo`, `immagine`) VALUES (5, 'Confezione Olio Extravergine di oliva 500ml', 'oli','SCATOLA DA 6 BOTTIGLIE DI VETRO DA 250 ML CON TAPPO ANTIRABBOCCO ( TOT 3 LITRI )',20,'72' ,'olio_extravergine_oliva_500_scatola.jpg');
INSERT INTO `uliveto`.`prodotti` (`id`, `nome`, `categoria`,`descrizione`,`stock`, `prezzo`, `immagine`) VALUES (6, 'Ceci secchi 500g', 'ceci','Tipicità di pregio del patrimonio agroalimentare del Parco Nazionale de Cilento. ',0,'6' ,'ceci_500.jpg');
INSERT INTO `uliveto`.`prodotti` (`id`, `nome`, `categoria`,`descrizione`,`stock`, `prezzo`, `immagine`) VALUES (7, 'Ceci secchi 1Kg', 'ceci','Tipicità di pregio del patrimonio agroalimentare del Parco Nazionale de Cilento. ',20,'11' ,'ceci_500.jpg');
INSERT INTO `uliveto`.`prodotti` (`id`, `nome`, `categoria`,`descrizione`,`stock`, `prezzo`, `immagine`) VALUES (9, 'Orcio Magnum Biscotto', 'orci','Orcio in ceramica contenente i profumi e i sapori del nostro Olio extravergine di oliva ottenuto direttamente dalle olive e unicamente mediante processi meccanici.',20,'65' ,'orcio-biscotto.jpeg');

COMMIT;

